#!/bin/bash

# source the environment variables
. ~/setenv

# create Docker build VM
# Optional - specify a DNS prefix (must be unique)
# --public-ip-address-dns-name yourdnsprefix
az vm create -g $ACRRG \
-n docker \
--size standard_d2s_v3 \
--nsg-rule SSH \
--image UbuntuLTS \
--os-disk-size-gb 128 \
--admin-username aks \
--custom-data docker/startup.sh

export DHOST=aks@`az network public-ip show -g $ACRRG -n dockerPublicIP --query [ipAddress] -o tsv`
echo " "
echo $DHOST
